### ISSUE TITLE
Plugin fails to activate on v3.1.stable.official

### ISSUE THREAD

**Issue by axeldeau** [need12648430/godot3-scene-notes#1]
Plugin > Activate prompts:

` res://addons/scene_notes/dock.gd:10 - Parse Error: The property 'dock_scene' is not present on the inferred type 'self' (but may be present on a subtype). (warning treated as error)
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/scene_notes/scene_notes.gd:1 - Parse Error: Script not fully loaded (cyclic preload?): res://addons/scene_notes/dock.gd
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR`

Let me know if you need more details.

Regards

**Comment by need12648430** [comment]
Can't seem to reproduce this. Did you install it through the Asset Library or by downloading from the repo?

**Comment by axeldeau** [comment]
Yes I did, it might be because I enabled "warning treated as error"

**Comment by need12648430** [comment]
Possibly. I'll try that and see what I can do.

**Comment by need12648430** [comment]
I can reproduce it now, but these aren't actually bugs. I just didn't write the addon strictly enough to satisfy all warnings.

After disabling 'Treat Warnings As Errors,' it works fine.

**Comment by axeldeau** [comment]
Ok thank you :-)
