### ISSUE TITLE
Notes are not actually saved until exit

### ISSUE THREAD

**Issue by youreperfect** [need12648430/godot3-scene-notes#2]
Currently the scene-notes.ini file is not actually updated until the plugin unloads at application exit, leading to potential data loss in the case of non-standard application or plugin exits.

I changed scene_notes.gd save_notes() function like below

```
func save_notes():
	if ! len(instance.get_node("Content/Editor").text):
		notes.erase_section(current_scene)
                save_config("scene-notes.ini", notes)
		return
	
	notes.set_value(
		current_scene,
		"note",
		instance.get_node("Content/Editor").text
	)
	save_config("scene-notes.ini", notes)
```

**Comment by need12648430** [comment]
Fixed. Thank you.
