### ISSUE TITLE
Scene must be changed or closed to save notes

### ISSUE THREAD

**Issue by youreperfect** [need12648430/godot3-scene-notes#3]
Currently if you press Ctrl-S to save your current scene the note changes you may have made are not updated. So if you open Godot editor and edit notes on the default scene then exit you will loose your work. Here is how I fixed it (combined with my save file fix in #2 )

all edits in scene_notes.gd:

around like 52 add a connection to a new function called scene_saved
```
	connect("scene_changed", self, "scene_changed")
	connect("scene_closed", self, "scene_closed")
	connect("resource_saved", self, "scene_saved")
```

around like 71 add the matching disconnection
```
disconnect("resource_saved", self, "scene_saved")
```

somewhere in the file add the scene_saved function:
```
# save notes for the open scene when the scene is saved
func scene_saved(res):
	if res.resource_path == current_scene or res.resource_path == "res://default_env.tres":
		save_notes()
```

you have to check for default_env.tres, for some reason godot gives this as the resource name when using a defalt scene rather than giving the actual scene path

**Comment by need12648430** [comment]
Oops, accidentally closed this issue. It's not fixed yet I'll get to work on this right away.

**Comment by need12648430** [comment]
Fixed. Thank you for all the help, @youreperfect. :)
